name: digitalcontractsapp
description: A new Flutter project.

version: 1.1.0+2

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  dio: ^3.0.8
  dio_cookie_manager: ^1.0.0
  morpheus: ^1.2.2+1
  path_provider: ^1.5.1
  auto_size_text: ^2.1.0
  overlay_support: ^1.0.2
  esys_flutter_share: ^1.0.2
  shared_preferences: ^0.5.7
  package_info: ^0.4.0+13
  url_launcher: ^5.4.1
  permission_handler: '^4.2.0+hotfix.3'
  line_icons: ^0.2.0
  flutter_svg: ^0.18.0
  animated_floatactionbuttons: ^0.1.0
  google_fonts: ^1.1.0
  cached_network_image: ^2.2.0+1
  flutter_swiper: ^1.1.6
  json_annotation: ^3.0.1
  flutter_timetable_view: ^0.1.0
  flutter_secure_storage: ^3.3.1+1
  flutter_week_view: ^0.2.1+7
  time_range_picker : any
  image_picker: ^0.6.7+2
  flutter_native_image: ^0.0.5+2
  flutter_exif_rotation: ^0.2.7
  version: ^1.2.0

  # state management
  stacked: ^1.6.0
  stacked_hooks: ^0.1.2
  flutter_hooks: ^0.9.0
  # navigation
  auto_route: ^0.5.0
  stacked_services: ^0.4.4+1
  # inversion of control
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^1.10.0
  auto_route_generator: ^0.5.0
  injectable_generator: ^0.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/account/
    - assets/home/
    - assets/onboarding/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 600
        - asset: fonts/Poppins-Light.ttf
          weight: 500
        - asset: fonts/Poppins-Thin.ttf
          weight: 400